version: "3.9"
services:
  postgres:
    image: postgres:17.0-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
